### ISSUE TITLE
HTML to VNode converter?

### ISSUE THREAD

**Issue by sclee15** [davidmarne/wui_builder#18]
Hello.

I hope an automatic way to convert HTML into VNodes.

Thank you.

**Comment by davidmarne** [comment]
I feel like this would take quite a bit of work to get right. However, I could probably get something going that tries to do a conversion. It might not always kick out code that passes analysis, but I think that it would still be helpful to get started on a project or a port. You would just have to go in and manually tweak some to get everything passing analysis. I'll look into it.

**Comment by davidmarne** [comment]
Did a quick first pass and pushed it up here:
https://github.com/davidmarne/convert_to_wui

**Comment by davidmarne** [comment]
@jerold fyi
