### ISSUE TITLE
Case for allowing contextValue to be a different type from PCComponent's state type.

### ISSUE THREAD

**Issue by jerold** [davidmarne/wui_builder#21]
If I have a component in which I'd like to grab a specific context, I need to declare the State type of the PCComponent to that of the contextValue I'm grabbing. I'm not sure if there is a way for that component to then have it's own state, for holding onto an input value for example without offloading that responsibility/state to a child component.

Is there also a case where components might want to pull multiple contexts types out of the component tree? For instance pulling state out of an app level context, and an Item level context within the same child component?

**Comment by davidmarne** [comment]
For you first question, look towards using [CComponent](https://github.com/davidmarne/wui_builder/blob/master/lib/src/components/reduced_components.dart#L11). If your component doesn't have props look towards using [SCComponent](https://github.com/davidmarne/wui_builder/blob/master/lib/src/components/reduced_components.dart#L23)

For your second question, any component has access to a getter, [context](https://www.dartdocs.org/documentation/wui_builder/0.4.2/wui_builder/Component/context.html), that is the Map<String, dyanmic> that contains all context values. You can look up multiple values from context manually using that. The *CComponents are just for convenience.

**Comment by jerold** [comment]
Oh nice. :) Thanks for the links.
