### ISSUE TITLE
Router does not support hashes for routes during initial load

### ISSUE THREAD

**Issue by fuzzybinary** [davidmarne/wui_builder#27]
The Router component currently does not support routes using a hash during the initial load, and pub/webdev serve does not support path based routes, so in both cases your current location is lost during a reload.

This is because History's initialization of the path (the way it initially figures out where to go) currently reads:

`String _path = window.location.pathname;`

It may be better to change this to a Location and work out the conflicts in the resulting code, or have this initialize to `${window.location.pathname}${window.location.hash}`

I'm not actually sure which is the best approach, or if another approach would be better. Thoughts?

**Comment by davidmarne** [comment]
yo, I went ahead and wrote a hash based history implementation. This has been annoying me too. It was also a problem with the docs on github pages. 

You can now decide between PushHistory and HashHistory when creating a history provider. [example](https://github.com/davidmarne/wui_builder/pull/28/files#diff-72ff1b44c5dc51b3f34a3d1cea5fc770R12)

**Comment by fuzzybinary** [comment]
Tried HashHistory and it works like a charm. Thanks for the swift respones!
