### ISSUE TITLE
Pub build is not working for the example todo.

### ISSUE THREAD

**Issue by sclee15** [davidmarne/wui_builder#4]
Transform Dart2JS on wui_builder_todos|web/index.dart tried to load missing input wui_builder|lib/example/todos/web/packages/$sdk/lib/dart_shared.platform.
Build failed.

**Comment by davidmarne** [comment]
It builds fine for me :confused: 
I gave that error a google search and the closest issue I could fine was this
https://github.com/dart-lang/pub/issues/1376
So, seems like a long shot, but is there isn't any chance you cloned the repo into a folder named 'packages'?

**Comment by sclee15** [comment]
Yeah. that was the issue I cloned this package under the packages folder..
Oops. I didn't know dart had this limitation or rules.

**Comment by davidmarne** [comment]
lol weird
